# General Config
# --------------------------

server:
  port: 8080

spring:
  application:
    name: Unicomer Bank API
  profiles:
    default: dev
  jpa:
    open-in-view: false

application:
  title: Unicomer Bank API
  version: 0.0.1-SNAPSHOT
  api:
    version: v1
    base-path: /api

logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss
    level: '%5p'

jwt:
  private:
    key: classpath:app.key
  public:
    key: classpath:app.pub
