# General Config
# --------------------------

server:
  port: 8080

spring:
  application:
    name: Unicomer Bank API
  profiles:
    default: dev
  jpa:
    open-in-view: false

application:
  title: Bank API
  version: 0.0.1-SNAPSHOT

logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss
    level: '%5p'
